coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

flags:
  py3.10:
    carryforward: true
  py3.11:
    carryforward: true
  py3.12:
    carryforward: true
  py3.13:
    carryforward: true

flag_management:
  default_rules:
    carryforward: true
